### ISSUE TITLE
[RFC] Remove Dependency on Python

### ISSUE THREAD

**Issue by winmillwill** [docopt/docopts#9] opened 2015-06-19 14:12 UTC
If I'm using bash, it's a strong indicator that I can't use Python or any other scripting language. The key use that I have for bash scripts is to automate existing manual tasks on servers that I can't change. I don't know how much work it would entail to port 'all the way' to bash. Conversely, if we want to replace getopt, then maybe we should provide a self-contained binary so that it's possible to download and execute it without help from the package manager, or at least without having to wrangle both the OS package manager AND the language package manager(s).

Thoughts?

**Comment by Sylvain303** [comment] 2015-07-02 06:07
Yep. A great chalenge to pass a docopts in full bash (other shell will be asked too, I guess). 

(My own tips, not totally related to your RFC)

For legacy server (servers that I can't change), what I do, is to have remote scripts sshed on the sever and run remotely. So the legacy server can be managed by an uptodate server handling everything for you, including git, unittesting, python, or more…

(end of disruption)

Other docopt support (not python based) are using option parsing generator. Which could mean that the parser could be generated, like a make or build your bash "self-contained binary". Now your legacy problem stay, you will have to build your script on a remote server and upload it on the legacy server.

Writing a parser in full bash will be painful, and will run quite slowly. 
Also, is it a good idea to put such effort for legacy stuff?

**Comment by CristianCantoro** [comment] 2016-12-28 15:36
My 2 cents; the problem is not so much having python installed, but being able to install packages (and in this case installing `docopt`), i.e. having root access. If I get it correctly this problem is addressed in https://github.com/docopt/docopts/issues/7.

**Comment by Sylvain303** [comment] 2017-01-10 06:30
Some wake up here… ;)

So my proposal in #7 was to build the docopts lib. And embed python code inside. So the python code of docopt is still required to work in the bash version, in fact it is installed on your workstation or an intermediate build Linux server. I guess that python is installed on the server already. If not, it may be too legacy. To be discussed else where.

Installing python and python's package is possible in user space, no root access needed. But could be painful or too much for non python user (user doesn't mean developer here), but note that it could be automated in some way, but could require some privileges.

Another built "docopt lib" (non python) could be shipped, a bit like cross compiling. I maintain that, programming a text parser in bash (or other) shell, is may be too much effort, and very slow. (you cant try to compare [jq](https://stedolan.github.io/jq/) vs [JSON Bash](https://github.com/dominictarr/JSON.sh) to have a good feeling)  If we try to address the problem of legacy environment. A no python environment is another problem.

What other reason could be pushed to remove python dependency? 

Also note that @winmillwill  issue, mention the package manager that could be used to install a "binary", I read here: autonomous program. Not necessarily a binary compiled parser. The [C version ](https://github.com/docopt/docopt.c) is generating a dedicated version of the option parser.

Could you define more precisely the constrain that would require the total remove of a python parser.

**Comment by CristianCantoro** [comment] 2017-01-10 16:20
> Installing python and python's package is possible in user space, no root access needed. But could be painful or too much for non python user (user doesn't mean developer here), but note that it could be automated in some way, but could require some privileges.

I concur. In fact, this is why I created a pull request to add `docopts` to Homebrew/Linuxbrew (see https://github.com/Homebrew/homebrew-devel-only/pull/60). In this way you should be able to do simply:
```
$ brew install docopts
```
as your (non-privileged) user and then have it installed within (a subfolder of) your home directory, so that you can use it as usual.

Under the hood what `brew` does is creating a virtualenv (see the formula: [docopts.rb#L28-L31](https://github.com/CristianCantoro/homebrew-devel-only/blob/86f5a48a86204a7acb15391a9ba3a248394bbf70/Formula/docopts.rb#L28-L29)) where `docopt` v.0.6.1 is installed. Homebrew, then takes care of copying the binary in a place that already part of your `PATH` ([docopts.rb#L33](https://github.com/CristianCantoro/homebrew-devel-only/blob/86f5a48a86204a7acb15391a9ba3a248394bbf70/Formula/docopts.rb#L33)) and do some testing ([docopts.rb#L36-L45](https://github.com/CristianCantoro/homebrew-devel-only/blob/86f5a48a86204a7acb15391a9ba3a248394bbf70/Formula/docopts.rb#L36-L45)).

As of now I have two issues;
* without a tagged revision I can not have a PR merged in core ([Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core/)), but in the devel-only repo which is currently deprecated (and my PR has been rejected (https://github.com/Homebrew/homebrew-devel-only/pull/60)), hence https://github.com/docopt/docopts/issues/10.
* from the CI results, several test fail for `docopts` fail on Mac (alas, I can not recover the link with the results). On Linux I still have test no. 104 failing (https://github.com/docopt/docopts/issues/6).

I hope I am not too much off-topic.

**Comment by Sylvain303** [comment] 2017-01-11 10:55
@CristianCantoro thanks for linking topic together. For my point of view the main point is legacy here:

"I have for bash scripts is to automate existing manual tasks on servers that I can't change"

I suspect Linuxbrew will not address this issue, as it may not be able to be installed neither on "servers that you can't change" (Aka legacy server).

I upped #5 some we could step into some proposal fixing multiple issue.

**Comment by Sylvain303** [comment] 2018-05-29 16:08
@winmillwill I produced an alpha version in golang, you may test it if you want.

https://github.com/Sylvain303/docopts/tree/docopts-go

**Comment by Sylvain303** [comment] 2018-06-18 16:44
Hi, fixed with #13. 

Now we have a binary, build in go. No mode code or lib dependency.

Just try it.

**Closed by Sylvain303** 2018-06-18 16:44 UTC
